baseURL = "https://peter0x44.github.io/"
languageCode = "en-us"
title = "File Descriptor Two"
theme = "PaperMod"
copyright = "© 2025 Peter0x44"

# Use YAML for front matter by default
metaDataFormat = "yaml"

[params]
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true

[params.utterances]
  repo = "peter0x44/peter0x44.github.io"
  issueTerm = "pathname"
  label = "utterances_comments"
  theme = "preferred-color-scheme"

[params.footer]
  text = ""

[params.homeInfoParams]
  Title = "File Descriptor Two"
  Content = "Peter0x44's technical musings"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]
